# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 18:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20171127_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
