# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_auto_20171127_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='recordatorio',
            field=models.BooleanField(default=False),
        ),
    ]
