# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 00:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_reserva_recordatorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'verbose_name': 'Agenda cargada por categoria', 'verbose_name_plural': 'Agendas cargadas por Categorias'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Agenda Reservada', 'verbose_name_plural': 'Agendas Reservadas'},
        ),
    ]
