# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_auto_20180117_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='especialidad',
        ),
    ]
