# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-18 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transversal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Modulo', 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Solicitante', 'verbose_name_plural': 'Solicitantes'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Sub Categoria', 'verbose_name_plural': 'Sub Categorias'},
        ),
        migrations.AlterModelOptions(
            name='tipocliente',
            options={'verbose_name': 'Tipo de Modulo', 'verbose_name_plural': 'Tipos de Modulos'},
        ),
        migrations.AlterModelOptions(
            name='tipoprofesional',
            options={'verbose_name': 'Tipo de Subcategoria', 'verbose_name_plural': 'Tipos de Subcategorias'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
