# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transversal', '0002_auto_20180117_2159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Establecimiento', 'verbose_name_plural': 'Establecimientos'},
        ),
    ]
