# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transversal', '0003_auto_20191123_2224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Sub Categoria', 'verbose_name_plural': 'Profesional'},
        ),
        migrations.AlterModelOptions(
            name='tipoprofesional',
            options={'verbose_name': 'Tipo de Subcategoria', 'verbose_name_plural': 'Tipos de Profesionales'},
        ),
    ]
