# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2020-02-01 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transversal', '0004_auto_20191126_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipoprofesional',
            options={'verbose_name': 'Tipo de Subcategoria', 'verbose_name_plural': 'Tipos de Progesionales'},
        ),
    ]
